name: Deploy to Vercel

on:
  push:
    branches: [main, dev]

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Install Vercel CLI
        run: npm install -g vercel

      - name: Deploy to Vercel
        env:
          # you stored the token as VERCEL_TOKEN_KLEVA; expose it as VERCEL_TOKEN for the CLI
          VERCEL_TOKEN: ${{ secrets.VERCEL_TOKEN_KLEVA }}
          VERCEL_ORG_ID: ${{ secrets.VERCEL_ORG_ID }}
          VERCEL_PROJECT_ID: ${{ secrets.VERCEL_PROJECT_ID }}
        run: |
          if [ -z "${VERCEL_TOKEN:-}" ]; then
            echo "VERCEL_TOKEN is empty. Check your GitHub Secrets."
            exit 1
          fi

          if [ "${{ github.ref }}" = "refs/heads/main" ]; then
            vercel pull --yes --environment=production --token="${VERCEL_TOKEN}"
            vercel --prod --confirm --token="${VERCEL_TOKEN}"
          else
            vercel pull --yes --environment=preview --token="${VERCEL_TOKEN}"
            vercel --confirm --token="${VERCEL_TOKEN}"
          fi
